version: '3.8'

services:
  database:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_DB: fire_department
      POSTGRES_USER: fire_admin
      POSTGRES_PASSWORD: secure_fire_db_password_2024
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U fire_admin -d fire_department"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  backend:
    build: 
      context: .
      dockerfile: Dockerfile.backend
    restart: always
    environment:
      NODE_ENV: production
      PORT: 5000
      DB_HOST: database
      DB_PORT: 5432
      DB_NAME: fire_department
      DB_USER: fire_admin
      DB_PASSWORD: secure_fire_db_password_2024
    ports:
      - "5000:5000"
    depends_on:
      database:
        condition: service_healthy

volumes:
  postgres_data:
    driver: local
